site_name: Data Programming
site_url: https://dataprogpy.github.io
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/table-heart
  favicon: assets/images/dataset_24dp_4B77D1_FILL0_wght400_GRAD0_opsz24.png
  features:
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - navigation.tabs
    - navigation.path
    - navigation.expand
    - navigation.indexes
    - navigation.tracking
    - navigation.footer
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    # - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight

copyright: Copyright &copy; 2025 Midhubalan Balasubramanian
repo_url: https://github.com/dataprogpy/code-samples
repo_name: dataprogpy/code-samples
extra:
  generator: true
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/midhubalan
    - icon: fontawesome/brands/github-alt
      link: https://github.com/midhubalan 

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
        #primary: indigo
        #accent: indigo

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        #primary: indigo
        #accent: indigo

plugins:
  - tags
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_themed: false
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false

markdown_extensions:
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - abbr
  - attr_list
  - pymdownx.blocks.caption
# Emoji config
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
# Mermaid markdown config for diagrams
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
# Code block display config
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  # Tabbed content
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  # Formatting text
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
nav:
  - Home: index.md
  - Syllabus: 
    - syllabus/index.md
    - Course Description: syllabus/course-description.md
    - Course Materials: syllabus/course-materials.md
    - Grading & Evaluation: syllabus/grading.md
    - Project Guide: syllabus/project-guide.md
    - Schedule: syllabus/schedule.md
    - Course Policies: syllabus/course-policies.md
  - Getting Started:
    - getting-started/index.md
    - Introduction to Colab: 
      - getting-started/colab/index.md
      - Getting Started with Colab: getting-started/colab/colab-intro.md
      - Colab Interface: getting-started/colab/colab-interface.md
      - Kernel State: getting-started/colab/kernel-state.md
      - Working with Data & Files in Colab: getting-started/colab/data-files.md
      - Essential Techniques: getting-started/colab/essential-techniques.md
      - Going Deeper: getting-started/colab/going-deeper.md
      - Best Practice & Getting Help: getting-started/colab/best-practice.md
    - Introduction to Pyhon:
      - getting-started/python/index.md
      - Why Python?: getting-started/python/why-python.md
      - Modeling Information: getting-started/python/modeling-information.md
      - Modeling Structures: getting-started/python/modeling-structures.md
      - Polars Teaser: getting-started/python/polars-teaser.md
      - Task Automation: getting-started/python/task-automation.md
      - Structuring Code: getting-started/python/code-organization.md
      - Next Steps: getting-started/python/next-steps.md

  - Exploratory Data Analysis:
    - eda/index.md
    - Data Wrangling with Polars: eda/polars.md
    - Data Visualization with Altair: eda/altair.md
    - Data Storytelling: eda/data_storytelling.md
  - Introduction to Modeling:
    - modeling/index.md
    - Modeling with scikit-learn: modeling/modeling_intro.md
    - Supervised Learning: modeling/supervised.md
    - Unsupervised Learning: modeling/unsupervised.md
  - Advanced Data Types:
    - adv-data-types/index.md
    - Time Series Analysis: adv-data-types/time-series.md
    - Text Analysis: adv-data-types/text-analysis.md
  - Resources:
    - resources/index.md
    